### ISSUE TITLE
derive Clone for Tree and Node 

### ISSUE THREAD

**Issue by enomado** [Adanos020/egui_dock#105]
I want to make feature - different dock layouts, so i want this structures be Clonnable. 

If you worry about Tab requires to be also Clonnable - since `clone(x) =  deserialize(serialize(x))` it could be used with feature = "serde" easily,

**Comment by Jerrody** [comment]
> I want to make feature - different dock layouts, so i want this structures be Clonnable.
> 
> If you worry about Tab requires to be also Clonnable - since `clone(x) = deserialize(serialize(x))` it could be used with feature = "serde" easily,

Hm, sounds as a good suggestion.

**Comment by Adanos020** [comment]
Sounds good to me.

When you open a PR for this, make sure you request merging it to the `release-0.5` branch.

**Comment by lvaroqui** [comment]
I think Tree and Node are already clonable as of 0.4?
It was introduced in this commit: https://github.com/Adanos020/egui_dock/commit/66d9dd57736532367542840b02e77812cf3bfe99#diff-9794019b962b882943346745baf52516c9f655c4198f992f64bfdb6bd545f9d2

Note that derive implements `Clone` when Tab implements `Clone` so you don't need any serde trick! :slightly_smiling_face:

**Comment by lvaroqui** [comment]
@enomado can this ticket be closed then?

**Comment by Adanos020** [comment]
@lvaroqui I think it can actually
