### ISSUE TITLE
Save and restore dock state when closing and reopening the application

### ISSUE THREAD

**Issue by shunsukeoka** [Adanos020/egui_dock#117]
**Is your feature request related to a problem? Please describe.**
I find it inconvenient when the dock state is not saved upon closing the application, causing me to lose my preferred layout and settings.

**Describe the solution you'd like**
I would like a feature that automatically saves the state of the dock when the application is closed, and then restores that state when the application is reopened. This would help maintain a consistent user experience across different sessions.

**Describe alternatives you've considered**
I have considered manually saving and loading the dock state, but it would be more convenient if this process was automated.

**Additional context**
This feature would be beneficial for users who frequently close and reopen the application, as it would save them time and effort in setting up their preferred dock layout each time.

**Comment by lvaroqui** [comment]
Hi @shunsukeoka,

This feature is already available in egui_dock, the `Tree` structure implements the `serde::Deserialize` and `serde::Serialize` traits which allow easy serialization and de-serialization. Combined with the `persistence` feature of [eframe](https://docs.rs/eframe/latest/eframe/trait.App.html#method.save) it is really easy to achieve persistence across sessions.

**Comment by shunsukeoka** [comment]
Hi,

I just wanted to express my gratitude for the persistence feature in egui_dock. I've successfully implemented it across sessions in my application. Your work has been incredibly helpful. Thanks!

As I've resolved the issue, I'll be closing it now. Keep up the great work!
