### ISSUE TITLE
How to specify drag-area size? (not separator style thickness)

### ISSUE THREAD

**Issue by EriKWDev** [Adanos020/egui_dock#125]
Hey! Really nice extension to egui :)

I see that I can specify a bunch of styles for my tabs, but how do I specify the drag area's size?

It can be hard to hit the exact line where I can drag and it would be nice to be able to make this area a bit larger and more forgiving to the pointer.

Note that I would like to do this without necessarily making the drawn line wider.

**Comment by Adanos020** [comment]
Hi, currently there isn't a way to do this, but nothing prevents us from adding an option like that.

**Comment by lvaroqui** [comment]
I'll take a crack at it :)

**Comment by Adanos020** [comment]
Closed by #128
