### ISSUE TITLE
Style.separator.interact_size

### ISSUE THREAD

**Issue by gre-v-el** [Adanos020/egui_dock#127]
For me it is always difficult to resize the layout when the separator width is set to 1px (default). I feel the most comfortable when it set to about 10px-15px, but then the ui looks ugly.

A new field, Style.separator.interact_size could represent the logical thickness of a separator and would not affect the graphical thickness (Style.separator.width).

**Comment by lvaroqui** [comment]
Duplicate of #125!

**Comment by Adanos020** [comment]
Closed by #128
