### ISSUE TITLE
Please Update to egui 0.22

### ISSUE THREAD

**Issue by Snowiiii** [Adanos020/egui_dock#131]
Hello! I wanted to inform you that Egui 0.22 was released yesterday. Although there weren't many changes, transitioning to the new version should be relatively straightforward. I personally use Egui and Egui Dock as well, and I'm interested in updating to 0.22. It would be great if you could update it and release a new version at your earliest convenience. Thank you! 😄

**Comment by Adanos020** [comment]
Hey, yes I'm going to make a new release today.
