### ISSUE TITLE
ScrollArea inside tab : panic with `attempt to add with overflow`

### ISSUE THREAD

**Issue by Gui-Yom** [Adanos020/egui_dock#133]
**Describe the bug**
Showing a tab with a Frame or a ScrollArea in anything other than the root node cause a panic.

**To Reproduce**
I made a minimal reproducer here : https://github.com/Gui-Yom/egui_dock_repro
Run with `cargo run`.

**Expected behavior**
No panic, like in `0.5.0`.

**Additional context**
I suspect the problem arise from this commit : https://github.com/Adanos020/egui_dock/commit/19c43ddaaef52531f1fecf2df583d767ac6bfdce in `src/widgets/dock_area/mod.rs`. Previously, the tabs were drawn after drawing the separators which  assigned them a tab rect that isn't infinite.

**Comment by lvaroqui** [comment]
I'll fix ASAP
