### ISSUE TITLE
Expand styling options for tabs

### ISSUE THREAD

**Issue by LennysLounge** [Adanos020/egui_dock#137]
**Is your feature request related to a problem? Please describe.**
The currently available styling options dont quite allow me to create a styling that closely follows the rest of the egui styling.

I have put together a simple panel to show what i would like to achieve.
This panel uses only `selectableLabel` and `Frame::group`.
![image](https://github.com/Adanos020/egui_dock/assets/25527438/7eb14936-e6bd-4673-ac86-69eacfcce2e9)

**Describe the solution you'd like**
1) Tabs required their own styling for active/inactive and hover.
Right now inactive tabs take on the color of the Tab bar. However it should be possible to seperate an active tab from an inactive tab from the tab bar from the panel background.

2) Tabs need a spacing style to seperate tabs from each other.
Tabs are very much pressed together right now. It would be nice to visually relax this by seprating the tabs a little.

3) Tab bodies need their own background color to seperate them from the tabs.
Technically not necessary but still usefull. Otherwise you have to create a new frame on top of the panel body with the actual background color you want.

4) Border around the dock area.
There exists a border style however it doesnt really work. It is somehow connected to the top margin.
In either case a border around the table would include the table bar.
You can already kinda do this with another frame around the `DockArea`. However if you have any rounding on the frame, the tabs will poke their corners through the border.

5) A Border around a tab body.
You can also do this by setting the `inner_margin` to zero and open a new frame inside the tab. However it would way nice if you could do this with a simple style instead.

**Comment by Adanos020** [comment]
These are great ideas, we should look into implementing them.

**Comment by LennysLounge** [comment]
I can open a PR if you like?

**Comment by Adanos020** [comment]
Yes please!

Before you do, check if any of the changes are breaking. If they are, open it for branch `release-0.7`, otherwise `main`.

**Comment by Adanos020** [comment]
Closed by #139
