### ISSUE TITLE
egui windows can move outside their node

### ISSUE THREAD

**Issue by RegenJacob** [Adanos020/egui_dock#14]
## egui windows have some weird behaviors inside nodes
![egui_dock](https://user-images.githubusercontent.com/53652728/184543007-804c9695-362a-4e33-9c52-f1d6d61d6f71.gif)

The Window can be moved outside of the node where it got created

**Comment by Jerrody** [comment]
Hm, I understand what's wrong, the problem is that each frame renders each tab and when you specify a window inside of tab implementation and window renders only when renders a tab.

**Comment by Jerrody** [comment]
I think that this should be promoted to the API change.
I don't know how to fast change it.

**Comment by RegenJacob** [comment]
> Hm, I understand what's wrong, the problem is that each frame renders each tab and when you specify a window inside of a tab implementation window renders only when the tab renders.

I'd say it's good that it doesn't render when the tab isn't visible but being able to move the window outside of the node is weird

**Comment by Jerrody** [comment]
> I'd say it's good that it doesn't render when the tab isn't visible but being able to move the window outside of the node is weird from a user perspective when you hide the tab and then reopen the tab and the window suddenly appears outside

Yes, I understand. Anyway, the new [tab](https://github.com/Adanos020/egui_dock/pull/6) API should also coverage this.

**Comment by Adanos020** [comment]
From my perspective `Window` is supposed to be an independent floating window, rather than being constrained by the area of a `Ui`. So I'm not sure what would be the appeal of creating one in a tab anyway.

If we want this kind of behaviour then we need a different widget. Because of that I think this is out of #6's scope.

**Comment by boonkerz** [comment]
is this status in git?

**Comment by Adanos020** [comment]
> is this status in git?

Sorry, what status?

**Comment by boonkerz** [comment]
i have compiled the experimental branch but i can not move the tab outside?

**Comment by Adanos020** [comment]
Oh, interesting. I haven't made any explicit changes for that :thinking:

**Comment by RegenJacob** [comment]
> i have compiled the experimental branch but i can not move the tab outside?

I meant that you can't move a egui::window outside of a node

**Comment by RegenJacob** [comment]
This might be relevant:
- https://github.com/emilk/egui/issues/2042

**Comment by boonkerz** [comment]
> > i have compiled the experimental branch but i can not move the tab outside?
> 
> I meant that you can't move a egui::window outside of a node

yea

**Comment by lvaroqui** [comment]
I personally don't think this is a bug, the behavior is the same in egui when nesting a window into another window, a collapsible header etc... Window are just not supposed to be constrained by UI that creates them.

**Comment by Adanos020** [comment]
Agreed, if you want windows independent from tabs, create them elsewhere. And even if we wanted windows constrained by tab areas, it's something for `egui` to implement.
