### ISSUE TITLE
Dock doesn't appear to have a size set after crate update

### ISSUE THREAD

**Issue by Speak2Erase** [Adanos020/egui_dock#142]
**Describe the bug**
Pre 0.5 placing a DockArea inside a `ui.group` would have it be surrounded by a separator as is the norm in egui. After updating the crate, that behavior no longer works (see screenshots).
Pre 0.5 placing a DockArea inside a window would work fine, now it draw outside of the window boundaries.

**To Reproduce**
See [luminol's tab view](https://github.com/Astrabit-ST/Luminol/blob/master/src/luminol.rs#L99) and [script editor](https://github.com/Astrabit-ST/Luminol/blob/master/src/windows/script_edit.rs#L98).

**Screenshots**
![luminol_kV8UMr9y9K](https://github.com/Adanos020/egui_dock/assets/54482069/14f6e19b-d1f4-4799-9130-d4a480c3f64c)
![image](https://github.com/Adanos020/egui_dock/assets/54482069/69312d7e-05b7-4294-b618-910b1aece17b)

**Comment by Adanos020** [comment]
Hm, this might be caused by #141

**Comment by Adanos020** [comment]
Hey, does this only happen in 0.6, or 0.5 as well?

**Comment by Speak2Erase** [comment]
Lemme try 0.5, iirc it does

**Comment by Speak2Erase** [comment]
It happens in 0.5, yeah

**Comment by Adanos020** [comment]
Gotcha, thanks for confirming.

**Comment by Adanos020** [comment]
@Speak2Erase actually, I have an idea. Are you using `show` or `show_inside`?

`show_inside` takes `&mut Ui` as a parameter, so it should render the `DockArea` within the border.

**Comment by Speak2Erase** [comment]
I'm using `show_inside`

**Comment by Adanos020** [comment]
Ok, that's definitely a bug then. Thanks

**Comment by Adanos020** [comment]
I attempted to reproduce this in the `hello.rs` example with `egui_dock` 0.6.2 by wrapping the `DockArea` in `ui.group`, like this:

```rs
ui.group(|ui| {
    DockArea::new(&mut self.tree)
        .style(style)
        .show_close_buttons(self.context.show_close_buttons)
        .show_add_buttons(self.context.show_add_buttons)
        .draggable_tabs(self.context.draggable_tabs)
        .show_tab_name_on_hover(self.context.show_tab_name_on_hover)
        .show_inside(ui, &mut self.context);
});
```

The result:

![image](https://github.com/Adanos020/egui_dock/assets/2311185/a3f41855-efe4-4505-be26-0cc1cd28e868)

Am I missing something?

**Comment by Speak2Erase** [comment]
I'll have to try and write a repro then?

**Comment by Adanos020** [comment]
Sure, please do.

**Comment by Speak2Erase** [comment]
```rs
use eframe::egui;

struct App {
    tree: egui_dock::Tree<()>,
}

struct TabViewer {}

impl egui_dock::TabViewer for TabViewer {
    type Tab = ();

    fn title(&mut self, _: &mut Self::Tab) -> egui::WidgetText {
        "jkhfbdgvjhfdsbghjfsdhj".into()
    }

    fn ui(&mut self, _: &mut egui::Ui, _: &mut Self::Tab) {}
}

fn main() {
    let mut tree = egui_dock::Tree::new(vec![]);

    eframe::run_simple_native("egui dock test", Default::default(), move |ctx, _| {
        egui::CentralPanel::default().show(ctx, |ui| {
            ui.group(|ui| {
                egui_dock::DockArea::new(&mut tree).show_inside(ui, &mut TabViewer {});
            });
        });
    })
    .expect("failed to run test app");
}
```

```toml
[package]
name = "egui_dock_test"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.22"
egui_dock = "0.6.2"
```

Here's an extremely minimal reproduction. It produces this:
![image](https://github.com/Adanos020/egui_dock/assets/54482069/8b85ce23-e9d5-4f10-a97e-204d24027a8f)

**Comment by Speak2Erase** [comment]
With lots of tabs too:
![image](https://github.com/Adanos020/egui_dock/assets/54482069/2fab3bc4-dd53-42bc-b413-7575ddea0aa0)

**Comment by Adanos020** [comment]
Awesome, thank you! Will look into it.

**Comment by Adanos020** [comment]
Ok, this is a very dumb bug with an easy fix. In `DockArea::allocate_area_for_root`:

```rs
fn allocate_area_for_root(&mut self, ui: &mut Ui) {
    let style = self.style.as_ref().unwrap();
    let mut rect = ui.available_rect_before_wrap();

    if let Some(margin) = style.dock_area_padding {
        rect.min += margin.left_top();
        rect.max -= margin.right_bottom();
        ui.painter().rect(
            rect,
            margin.top,
            style.separator.color_idle,
            Stroke::new(margin.top, style.border.color),
        );
    }

    if self.tree.is_empty() {
        ui.allocate_rect(rect, Sense::hover()); // <------ THIS SHOULDN'T BE IN THIS BRANCH
        return;
    }

    self.tree[NodeIndex::root()].set_rect(rect);
}
```

I'll open a PR fixing this.

**Comment by Adanos020** [comment]
@Speak2Erase could you test if the `fix-dockarea-in-group` branch fixes this?

**Comment by Speak2Erase** [comment]
Yeah, that fixes the grouping issue!
It also seems to fix the window issue too.

**Comment by Adanos020** [comment]
Awesome, I'll merge it and publish a new patch. Thanks for helping me with it!
