### ISSUE TITLE
Allow close button to be hidden on specific tabs, and prevent dragging of specific tabs

### ISSUE THREAD

**Issue by learnplaycreate** [Adanos020/egui_dock#161]
**Is your feature request related to a problem? Please describe.**
No problem just looking for some additional functionality

**Describe the solution you'd like**
I want to be able to hide the close button on specific tabs and also prevent specific tabs from being dragged. 
The use case I have is I have a center panel that I need to remain in the center, but all the tabs on the sides and bottom can be moved as required. 

Additionally I'd also like to be able to hide the title for the tabs that i'm preventing from dragging - but that's not really the topic of this request - i'll look into that later. 

**Describe alternatives you've considered**
can't really think of a way to deliver the use cases i'm trying to build in a different way. 

**Additional context**
i've made the change in my forked branch, just really want to know if you're interested in including the functionality into the crate. 
i'll make a PR - happy to make improvements, or changes to the way i've implemented it if it'll allow you to include it, 
also understand that this might not be a use case that you're interested, so really just putting it up in case you want it.

**Comment by Adanos020** [comment]
We already have this feature in the `release-0.7` branch. See #150
