### ISSUE TITLE
Adding tabs in floating windows does not respect surface

### ISSUE THREAD

**Issue by knoellle** [Adanos020/egui_dock#166]
**Describe the bug**

The tab_add feature only works on the main surface.
This is because `TabViewer::on_add` does not know which surface the tab belongs to.

**To Reproduce**
1. run `cargo run --example tab_add`
2. Drag any tab to make it pop out into an floating egui window
3. Click on the `+` button next to the popped out tab
4. Instead of inside the window, the new tab is spawned in the first tree leaf of the main surface.

**Expected behavior**
The tab should be added to the floating window, but as far as I know, this is currently not possible to implement.

**Screenshots**
![egui_dock_tab_add_floating_window](https://github.com/Adanos020/egui_dock/assets/33729490/2769f76a-739e-46a0-b2d6-03cb8d21887d)

**Additional context**
Ideally the node indices would be unique across the whole DockState structure or `TabViewer::on_add` should be passed the surface index.

**Comment by Adanos020** [comment]
Nicely spotted, we'll look into it.
Glad to see someone is testing the release branches :smile:

**Comment by Adanos020** [comment]
Fixed by #167

**Comment by knoellle** [comment]
Perfect, thanks for the quick response! ❤️ 
Now all I need is popping out to an actual window :D

**Comment by Adanos020** [comment]
That would be trickier but who knows, maybe someone eventually implements proper multi-viewport support for egui :)
