### ISSUE TITLE
v0.7 Release Branch: Reordering tabs doesn't work anymore

### ISSUE THREAD

**Issue by njust** [Adanos020/egui_dock#172]
Reordering tabs via the tab bar doesn't work anymore.

**To Reproduce**
This can be reproduced via the "simple" example here
https://github.com/Adanos020/egui_dock/blob/release-0.7/examples/simple.rs

https://github.com/Adanos020/egui_dock/assets/2380253/24f6d073-d02d-4ea3-9e3e-4f958fa84a65

**Expected behavior**
Reordering tabs was working in egui_dock 0.6.3:

https://github.com/Adanos020/egui_dock/assets/2380253/3a8de415-f618-4325-9443-d96cd0aade80

**Comment by Adanos020** [comment]
Fixed by #173
