### ISSUE TITLE
Dragging tabs not working on release-0.7 with Wasm

### ISSUE THREAD

**Issue by ToppDev** [Adanos020/egui_dock#174]
**Describe the bug**
When running egui_dock examples as Wasm in the browser, it is not possible anymore to drag and drop tabs on the `release-7.0` branch.

**To Reproduce**
1. I created 2 branches on my fork with changes to run the current `main` and `release-0.7` branch on wasm.
    1. Working `main` branch https://github.com/ToppDev/egui_dock/tree/wasm_main
    2. Not working `release-0.7` branch https://github.com/ToppDev/egui_dock/tree/wasm_release-7.0
3. I copied the `simple.rs` example as `src/main.rs` and adapted it for Wasm. Follow the `eframe_template` web instructions to run it https://github.com/emilk/eframe_template/#web-locally. If you already did, start the program with
    ```bash
    trunk serve
    ```
5. Take a browser (I use Chrome) and navigate to `http://127.0.0.1:8080/index.html#dev`
6. Try to drag tabs around

**Expected behavior**
Tabs are draggable.

**Current behavior**
The whole website freezes when dragging tabs around.

**Comment by Adanos020** [comment]
Interesting, for me (using Firefox) on `wasm_release7.0` it doesn't even display any GUI.

We can't publish release 0.7 before this gets fixed.

**Comment by ToppDev** [comment]
Firefox has a weird behavior, that you need to clear coockies and site data when you switch from one branch to the other and restart trunk.

Firefox is also freezing for me on the `wasm_release-7.0` branch

**Comment by Adanos020** [comment]
Thanks, after clearing the cookies it behaves just as you described.

**Comment by Adanos020** [comment]
Fixed by #176
