### ISSUE TITLE
Wasm on mobile/smartphones not working

### ISSUE THREAD

**Issue by ToppDev** [Adanos020/egui_dock#179]
**Describe the bug**
On mobile devices with touch screens, drag and dropping tabs around is not working. It does not work for `main` and `release-0.7` branch.

**To Reproduce**
1. Checkout one of my two branches of the current main or release-0.7 branch with a basic Wasm example.
    - `main` branch https://github.com/ToppDev/egui_dock/tree/wasm_main
    - `release-0.7` branch https://github.com/ToppDev/egui_dock/tree/wasm_release-0.7
2. Follow the eframe_template web instructions to run it https://github.com/emilk/eframe_template/#web-locally. If you already did, start the program with the following command (replace `<local-ip>` with your computer's local IP address)
```
trunk serve --address <local-ip>
```
3. Connect a smartphone to the same network as the computer (over Wifi)
4. Open a browser (I tested in chrome and firefox apps) and navigate to `http://<local-ip>:8080`
5. Try to drag tabs around

**Expected behavior**
Tabs can be dragged to create new splits.

**Screenshots**

https://github.com/Adanos020/egui_dock/assets/17766093/3a24545c-2b0c-4e0b-9d3f-33a270a5e3a1

**Comment by ToppDev** [comment]
I narrowed it down a little on the `main` branch.

In `src/widgets/dock_area/mod.rs` on line 220. The `i.pointer.any_released()` is never triggered
https://github.com/Adanos020/egui_dock/blob/03e5a66bc25129a339db349122e5b73d3a994d64/src/widgets/dock_area/mod.rs#L207-L224

**Comment by ToppDev** [comment]
Some further analysis:
- On PC in the browser, the release of the pointer is happening on the same frame, as the drag
- On mobile, the release is happening, but one frame after the last drag. So the event is not processed anymore.

Is this a problem with egui itself? If you think so, I will be glad to fill a bug report over at the egui repo.

**Comment by ToppDev** [comment]
I narrowed it further down. On mobile
- `self.drag_data` is still set in the frame, where `any_released` is triggered
- `self.hover_data` however is `None`

This comes down to the fact, that on touch screens, the `pointer.hover_pos()` is `None` on the frame, where `any_released()` is `true`.
https://github.com/Adanos020/egui_dock/blob/03e5a66bc25129a339db349122e5b73d3a994d64/src/widgets/dock_area/mod.rs#L1010

So I guess the hover position needs to be stored somehow to access the last known position? What are your thoughts on this?

**Comment by Adanos020** [comment]
Hey, thank you for such a detailed report and attempting to debug this.

> This comes down to the fact, that on touch screens, the `pointer.hover_pos()` is `None` on the frame, where `any_released()` is `true`.
> So I guess the hover position needs to be stored somehow to access the last known position? What are your thoughts on this?

If that's the case, then your solution seems worth trying. I'd just add another `Pos2` field to `DockState` and keep it updated on each update where `hover_pos()` is available.

**Comment by ToppDev** [comment]
That sound good, I will try it out and if it works, create a PR.

Should I create the PR on `main` or `release-0.7` or both?

**Comment by Adanos020** [comment]
Open it on `release-0.7`, I'm planning to publish the new version after this gets fixed 👍

**Comment by Adanos020** [comment]
Fixed by #180
