### ISSUE TITLE
Darktheme doesn't work properly

### ISSUE THREAD

**Issue by RegenJacob** [Adanos020/egui_dock#18]
![Peek 2022-08-15 03-58](https://user-images.githubusercontent.com/53652728/184565285-10bba4f6-5d10-45a8-aa3c-b73ab76dafed.gif)

My guess is that it happened in #6   
It would be useful to have a default dark theme

**Comment by Adanos020** [comment]
Yup, that definitely needs fixing.

**Comment by RegenJacob** [comment]
> Yup, that definitely needs fixing.

No it was just the hello example 

the simple example works as expected because it uses Style::default
