### ISSUE TITLE
Non-closable tabs can be closed by popping out

### ISSUE THREAD

**Issue by CryZe** [Adanos020/egui_dock#184]
**Describe the bug**
In the latest version you can pop out tabs into floating windows, which can be closed even if the tab is not meant to be closeable.

**To Reproduce**
```rust
use eframe::egui;
use egui_dock::{DockArea, DockState, NodeIndex};

struct Tab(char);

struct App {
    dock_state: DockState<Tab>,
}

fn main() {
    eframe::run_native(
        "Tab Closing Example",
        eframe::NativeOptions::default(),
        Box::new(|_| {
            let mut dock_state = DockState::new(vec![Tab('A'), Tab('F')]);
            let tree = dock_state.main_surface_mut();
            let [left, right] = tree.split_right(NodeIndex::root(), 0.65, vec![Tab('C')]);
            tree.split_below(right, 0.5, vec![Tab('D')]);
            tree.split_below(left, 0.5, vec![Tab('B'), Tab('E')]);

            Box::new(App { dock_state })
        }),
    )
    .unwrap();
}

struct TabViewer;

impl egui_dock::TabViewer for TabViewer {
    type Tab = Tab;

    fn ui(&mut self, _: &mut egui::Ui, _: &mut Self::Tab) {}

    fn title(&mut self, tab: &mut Self::Tab) -> egui::WidgetText {
        format!("Tab {}", tab.0).into()
    }
}

impl eframe::App for App {
    fn update(&mut self, ctx: &eframe::egui::Context, _: &mut eframe::Frame) {
        DockArea::new(&mut self.dock_state)
            .show_close_buttons(false)
            .show(ctx, &mut TabViewer);
    }
}
```
with
```toml
eframe = "0.22.0"
egui_dock = "0.7.0"
```

**Expected behavior**
I should not be able to close it.

**Screenshots**
![https://i.imgur.com/E6u7SVF.gif](https://i.imgur.com/E6u7SVF.gif)

**Comment by CryZe** [comment]
Ah nvm it seems like there's a separate function I need to call for ensuring the windows can't be closed. Not sure if that maybe should be implied.

**Comment by Adanos020** [comment]
Hey, this isn't a bug. With `DockArea::show_close_buttons` you're only disabling the close buttons, which doesn't make the tabs not closable: you can close them by e.g. clicking on them with the middle mouse button.

If you want to make a tab uncloseable, you'll need to override `TabViewer::closeable` and return false. If you do that, the close button will be disabled on a window containing a tab for which `closable` returns false.

Let me know if you need more help!

**Comment by Adanos020** [comment]
The documentation on the other hand does indeed need to be corrected, as it's misleading.

![image](https://github.com/Adanos020/egui_dock/assets/2311185/ae25b1fe-a25e-41b1-a344-f7cfbf6f5b30)
