### ISSUE TITLE
Still able to turn non-windowable tab into a window via context menu

### ISSUE THREAD

**Issue by simon-peregrine** [Adanos020/egui_dock#187]
**Describe the bug**
Even when `allowed_in_windows` returns false, the context menu has an Eject button that pops the tab out into a window.

**To Reproduce**
Steps to reproduce the behavior (confirmed on `main` branch):
1. Implement `allowed_in_windows` of `TabViewer` and return false.
2. Observe that a tab can no longer be dragged out into a new window, but that the same behaviour can still be achieved by right-clicking on the tab and clicking "Eject".

**Expected behavior**
No eject button should be added to the context menu for non-windowable tabs.

**Comment by Adanos020** [comment]
Oh, what an oversight :D 

Thanks for reporting, luckily this won't be difficult to fix.
