### ISSUE TITLE
egui Panels have weird behavior

### ISSUE THREAD

**Issue by RegenJacob** [Adanos020/egui_dock#19]
![Peek 2022-08-20 17-23](https://user-images.githubusercontent.com/53652728/185754375-3b4f7cc1-fad6-401e-91ba-dee0d904c5e1.gif)

egui::SidePanel inside a tab/node 

egui::TopBottomPanel and egui::CentralPanel have the same issue

**Comment by Jerrody** [comment]
@RegenJacob 
Hello! Do you counter with your problem at the current moment?

**Comment by RegenJacob** [comment]
Yes the issue still exists

**Comment by lvaroqui** [comment]
Hello @RegenJacob,
Can you provide reproduction code?

I tested it and could not reproduce, do you use the `show_inside` method of CentralPanel?

My code:
```rust
impl egui_dock::TabViewer for TabViewer {
    type Tab = String;
    fn ui(&mut self, ui: &mut egui::Ui, tab: &mut Self::Tab) {
        SidePanel::left(ui.id()).show_inside(ui, |ui| ui.label("Hello"));
        ui.label(format!("Content of {tab}"));
    }
}
```

Result:
![DeepinScreenshot_simple_20230325193715](https://user-images.githubusercontent.com/48593807/227735450-e21fe50b-7df1-478d-8c7f-96a76fcd7fd1.png)

**Comment by RegenJacob** [comment]
> Hello @RegenJacob,
> Can you provide reproduction code?
> 
> I tested it and could not reproduce, do you use the `show_inside` method of CentralPanel?
> 
> My code:
> ```rust
> impl egui_dock::TabViewer for TabViewer {
>     type Tab = String;
>     fn ui(&mut self, ui: &mut egui::Ui, tab: &mut Self::Tab) {
>         SidePanel::left(ui.id()).show_inside(ui, |ui| ui.label("Hello"));
>         ui.label(format!("Content of {tab}"));
>     }
> }
> ```
> 
> Result:
> ![DeepinScreenshot_simple_20230325193715](https://user-images.githubusercontent.com/48593807/227735450-e21fe50b-7df1-478d-8c7f-96a76fcd7fd1.png)
> 

It could have been fixed by now I will look at it when I have time (probably tomorrow)

**Comment by RegenJacob** [comment]
Ah it seems like that I accidentally used .show() instead of .show_inside()
