### ISSUE TITLE
Add `iter_tabs` and `iter_tabs_mut`

### ISSUE THREAD

**Issue by juh9870** [Adanos020/egui_dock#192]
**Is your feature request related to a problem? Please describe.**
I need to iterate over all tabs in my app, and I don't want my logic to handle internal docking structure with leaves.

**Describe the solution you'd like**
`iter_tabs` and `iter_tabs_mut` methods to directly iterate over tabs data

**Describe alternatives you've considered**
```rs
state
    .iter_nodes()
    .filter_map(|e| {
        if let Node::Leaf { tabs, .. } = e {
            Some(tabs)
        } else {
            None
        }
    })
    .flatten()
```
This requires my app to take internal docking logic in consideration, as well as makes `_mut` version impossible

**Comment by Adanos020** [comment]
Closed by #196
