### ISSUE TITLE
Add mutable versions of `iter_nodes` and `iter_main_surface_nodes`

### ISSUE THREAD

**Issue by juh9870** [Adanos020/egui_dock#193]
**Is your feature request related to a problem? Please describe.**
I need to iterate over all tabs and update data in them, but there is no sane way to do that right now.

**Describe the solution you'd like**
`mut` versions for `iter_nodes` and `iter_main_surface_nodes` nodes

**Describe alternatives you've considered**
#192 is what I actually need, but I think `iter_nodes_mut` might be useful as well

**Comment by eupraxia05** [comment]
Needed this for my project so I took a stab at it in #195.

**Comment by Adanos020** [comment]
Closed by #195.
