### ISSUE TITLE
Serialization broken with serde_json

### ISSUE THREAD

**Issue by knoellle** [Adanos020/egui_dock#197]
**Describe the bug**
(de)serialize with serde_json (and likely other serde libraries) is broken when tabs are popped out into separate egui window.

**To Reproduce**
1. Check out branch [`serialize-bug`](https://github.com/knoellle/egui_dock/tree/serialize-bug) in my fork.
2. `cargo run --example=hello --features serde`
3. Pop out one of the tabs into a floating window
4. Close app, state is stored in `~/.local/share/myeguiapp/app.ron`
5. Repeat step 2., stored state fails to deserialize properly

Result:
```
thread 'main' panicked at examples/hello.rs:534:54:
called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected f32", line: 1, column: 1526)
```

**Expected behavior**
Deserialization should restore the previously serialized state without error or significant loss of state.

**Screenshots**

**Additional context**
It seems that the `default()` impl of WindowState does not play nicely with serialization because it uses `Rect::NOTHING`.
Both `NOTHING` and `EVERYTHING` use `f32::INFINITY`, which serializes to `null` in serde_json. When deserializing, the `null` encountered is not considered a valid f32, causing an error.

**Comment by Adanos020** [comment]
I think turning `screen_rect` to `Option<Rect>` is the simplest solution.

To make sure this doesn't break anything, `WindowState::rect()` can be re-implemented as:
```rust
pub fn rect(&self) -> Rect {
    self.screen_rect.unwrap_or(Rect::NOTHING)
}
```

I'll make a PR with the fix.
