### ISSUE TITLE
`DockState<Tab>::remove_tab` may cause the whole program panic when the tab is the last tab of a window.

### ISSUE THREAD

**Issue by sakura6264** [Adanos020/egui_dock#206]
**Describe the bug**
when use remove_tab function to remove the last tab from a window, it could not close the window like clicking on the tab.
And in the next time I call `egui_dock::DockArea::show_inside`, the program panic.

**To Reproduce**
```rust
match self.tree.find_tab(&tab) {
                        Some(index) => {
                            self.tree.remove_tab(index);
                        }
                        None => {
                            self.tree.add_window(vec![tab]);
                        }
                    }
```

Is there any way to close the tab from rust code just like what it happens when I click the close button?

**Comment by Adanos020** [comment]
> Is there any way to close the tab from rust code just like what it happens when I click the close button?

Yes, you can override [`TabViewer::force_close`](https://docs.rs/egui_dock/latest/egui_dock/widgets/tab_viewer/trait.TabViewer.html#method.force_close).

**Comment by sakura6264** [comment]
This function works. Thanks very much.

**Comment by Adanos020** [comment]
Now to actually fix the issue: looks like tabs in windows aren't correctly deleted with `DockState::remove_tab`, leaving a `Surface` without a leaf node. We need to also delete the surface when that happens.
