### ISSUE TITLE
Can't drag windows back into main surface

### ISSUE THREAD

**Issue by liquidhelium** [Adanos020/egui_dock#221]
**Describe the bug**
When the main surface is empty, there seems are no ways to drag a window back into main surface, with no indicators showing up.

**To Reproduce**
1. Set up a `DockArea` with a tab.
2. Drag the tab so that it becomes a window. Now the main surface is empty
3. Then the window can't be dragged back into main surface.

**Expected behavior**
Maybe a dummy widget should show up in the main surface, so that we can recive mouse events on it.

**Comment by Adanos020** [comment]
Hi, sorry about that, looks like I didn't test the egui upgrade thoroughly enough. Looking into this now.
