### ISSUE TITLE
Content overlaps with another tab

### ISSUE THREAD

**Issue by lnenad** [Adanos020/egui_dock#233]
**Describe the bug**
I have an area that is manually positioned that contains a button. When I split the tabs horizontally so they sit one on top of another and resize so that button should become hidden by the bottom tab, the button stays visible and on top of the content from the bottom tab. 

**Expected behavior**
The content of the manually positioned area should be hidden by the overlapping tab background.

**Screenshots**

Before resize: 
<img width="190" alt="image" src="https://github.com/Adanos020/egui_dock/assets/8889498/962dcdd4-d1fc-49a5-afdc-ec8adf1a2c91">

After resize:
<img width="201" alt="image" src="https://github.com/Adanos020/egui_dock/assets/8889498/3b8d535c-c8b3-4193-a7cc-882e84f26966">

You see the button is still visible even though it should be clipped by the lower tab background.

**Comment by Adanos020** [comment]
Hey, if you're placing a widget manually, then it can't be clipped. Instead, consider using `ui.horizontal()` and putting a `ui.add_space(amount)` before the button. You can get the amount of horizontal space left using `ui.available_width()`.

Let me know if that helps.
