### ISSUE TITLE
Assert panic on dragging tab change its layer_id with egui `extra_asserts` feature turned on

### ISSUE THREAD

**Issue by enomado** [Adanos020/egui_dock#239]
**Describe the bug**
panicked at 'Widget changed layer_id during the frame'

**To Reproduce**
enable egui `extra_asserts` feature
start dragging some tab
asserting triggers in 
/egui_dock-0.12.0/src/widgets/dock_area/show/leaf.rs:259:32

**Additional context**
Probably this is absolutely normal, but may be not )

**Comment by Adanos020** [comment]
Fixed by #243
