### ISSUE TITLE
[`WINDOWS`] Currently examples cannot be built with `glutin`.

### ISSUE THREAD

**Issue by Jerrody** [Adanos020/egui_dock#26]
Due to this issue https://github.com/rust-windowing/glutin/issues/1454.

~~I think that this is `rustc` problem. So, I created an issue https://github.com/rust-lang/rust/issues/101377.~~

**Comment by Jerrody** [comment]
PIN THIS ISSUE.

**Comment by Adanos020** [comment]
Any ideas how this could be resolved?

**Comment by Jerrody** [comment]
> Any ideas how this could be resolved?

As mentioned [Chris Denton](https://github.com/ChrisDenton) in https://github.com/rust-lang/rust/issues/101384#issuecomment-1236171030:
> The most likely explanation would be the crate you're using has switched from winapi to windows-sys.

**Comment by Jerrody** [comment]
Or make a PR.

**Comment by Jerrody** [comment]
Oh, okay. They will yank a version https://github.com/rust-windowing/glutin/pull/1457. So, this will be fixed.

**Comment by Adanos020** [comment]
Ok, once the fixed version ends up in eframe, we'll upgrade it in this project.

**Comment by Jerrody** [comment]
> Ok, once the fixed version ends up in eframe, we'll upgrade it in this project.

I think that doesn't need to change anything I will wait until yank and will report the results.

**Comment by Jerrody** [comment]
@Adanos020 
That was fixed.

**Comment by Adanos020** [comment]
Great, thanks for bringing this up!
