### ISSUE TITLE
Problems with too many tabs / not enough space 

### ISSUE THREAD

**Issue by RegenJacob** [Adanos020/egui_dock#42]
![Peek 2022-09-21 19-45](https://user-images.githubusercontent.com/53652728/191574756-3f57534a-2b5d-441d-b81c-0ceeb1be7673.gif)

It's not possible to access tabs when there isn't enough space.

Maybe it would be possible to decrease the width of the tab or make it scrollable

**Comment by Adanos020** [comment]
A mixture of both seems to make the most sense. Tabs can shrink up to a certain point, and then the tab bar becomes scrollable.

**Comment by RegenJacob** [comment]
In #43 the add button overlaps with the tabs when there isn't enough space 
#65 fixes it for expand_tab but expand_tab messes with the titles

**Comment by RegenJacob** [comment]
![Id_clashes](https://user-images.githubusercontent.com/53652728/200946739-c1f57607-294a-4dd0-8990-44c6d1fc9332.gif)
 
Seems like expand_tabs crates id clashes when there isn't enough space

**Comment by Speak2Erase** [comment]
Hi, are there any plans to fix this?

**Comment by Adanos020** [comment]
@Speak2Erase Yes; to be honest we didn't prioritise this enough. Whenever someone finds time and comes up with a good solution this will be fixed.

**Comment by Speak2Erase** [comment]
@Adanos020 I wouldn't mind taking a shot at fixing it

**Comment by Adanos020** [comment]
@Speak2Erase Sure, please go ahead! This would be great to have.

**Comment by lvaroqui** [comment]
Hey @Speak2Erase,

I happened to work on this exact issue yesterday and came up with something simple (and very much wip). If you want to take a look I made a draft PR: https://github.com/Adanos020/egui_dock/pull/116

**Comment by Adanos020** [comment]
Closed by #116
