### ISSUE TITLE
Option for full-width tabs

### ISSUE THREAD

**Issue by adamgreig** [Adanos020/egui_dock#44]
Thanks so much for taking on egui_dock and publishing it!

I've been playing with making the tab bars look a bit more like the qt and pyqtgraph ones, where the tab widths expand to fill the tab bar, so that if there's only one tab it's more like a window with a title. In my application there's often lots of windows but rarely any tabs, so I prefer this style.

My experimental branch is [here](https://github.com/Adanos020/egui_dock/compare/main...adamgreig:egui_dock:expand-tabs), it didn't take many changes to hardcode this, though I think there might be a more elegant way to centre the title text in the tab. I wanted to check if there was interest in including this as an option in `Style`? Or even as the default style? I'd be happy to tidy the code up and open a PR if so.

Here's a screenshot of how it currently looks with the `traits` example:

![image](https://user-images.githubusercontent.com/47219/192658046-1d7b6250-619a-44fb-81be-1977fce51c68.png)

**Comment by Adanos020** [comment]
This looks great! Couple of things to consider:
- How will it play out with the + button?
- What happens when there are so many tabs that they become tiny? Related issue: #42

**Comment by adamgreig** [comment]
> * How will it play out with the + button?

Ah, from #43? I think just subtract the button width from the full tab bar width, I tried merging that PR (and just removing 24.0 [here](https://github.com/Adanos020/egui_dock/compare/main...adamgreig:egui_dock:expand-tabs#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R323)) and got:

![image](https://user-images.githubusercontent.com/47219/192887327-8c1bfa5c-080f-4e8c-8ae9-ca5954de5198.png)

> * What happens when there are so many tabs that they become tiny?

In some ways it's better, because each tab shrinks, so it's a bit like a browser up to a point, but once the contents of the tabs exceeds the available width per tab it doesn't look great. Eventually I guess we'd want something more sophisticated to permit scrolling through tabs or at least clipping the contents to the tab area or something.

![image](https://user-images.githubusercontent.com/47219/192887770-8c299e5f-3b1e-4f98-8579-bcc5b9e8aafc.png)
![image](https://user-images.githubusercontent.com/47219/192887804-ea81f4a8-5895-4f8a-aaf8-f90c2fa7ddd8.png)

I guess this is basically half of your suggestion from #42, i.e. the tabs will shrink but eventually we want to stop shrinking and start scrolling.

**Comment by Adanos020** [comment]
Cool, all of this seems fine for now. Once #42 gets fixed, all of this should be working great.

> I guess this is basically half of your suggestion from https://github.com/Adanos020/egui_dock/issues/42, i.e. the tabs will shrink but eventually we want to stop shrinking and start scrolling

Yup, also when the tabs become smaller than their titles, the title text should be cropped and, ideally, faded out to transparent.

**Comment by adamgreig** [comment]
Cool! Would you prefer I make this an option in Style or just change the current behaviour? If an option, I was thinking just a bool for "expanded tabs", which would then always have centered tab name text too.

**Comment by Adanos020** [comment]
Add a bool for it in `Style`, we want the look and feel to be as customizable as possible 👍
