### ISSUE TITLE
Inconsistency: `inner_margin` not part of `Style`

### ISSUE THREAD

**Issue by emilk** [Adanos020/egui_dock#64]
It took me a long time to find the settings for the inner margin, and that's because it is not where every other setting is.

**Comment by Adanos020** [comment]
Right, that's an oversight on my part. Shouldn't be too hard to move it to `Style`.

**Comment by msheldyakov** [comment]
@Adanos020 I'm trying to find where I can be helpful. Do you mind if I try to do this and open a pr?
https://github.com/emilk/egui/discussions/2234

**Comment by Adanos020** [comment]
@msheldyakov Sure, I haven't yet started working on this so feel free to go ahead!

**Comment by Adanos020** [comment]
Fixed by https://github.com/Adanos020/egui_dock/pull/67
