### ISSUE TITLE
Add in `README.md` guide about how to use `egui_dock` aka "quick start"

### ISSUE THREAD

**Issue by Jerrody** [Adanos020/egui_dock#73]
This is pretty hard to understand how to use `egui_dock` at beginner steps and would be good to write a guideline that explains step by step what needs to do to make it works and also cover usage cases of GAPI (Vulkan, OpenGL, and maybe-maybe DX12 (`rusty_d3d12`), but optional I'm not sure if it needs).

**Comment by RegenJacob** [comment]
> also cover usage cases of GAPI (Vulkan, OpenGL, and maybe-maybe DX12 (rusty_d3d12), but optional I'm not sure if it needs).

Things like this depend on the egui backend for example the eframe backend: using [glow](https://github.com/emilk/egui/tree/master/examples/custom_3d_glow) and [wgpu](https://github.com/emilk/egui/tree/master/crates/egui_demo_app) 
so rather then explaining this again we could just point to that

**Comment by Adanos020** [comment]
I agree with @RegenJacob because `egui_dock` is nothing more than just an extension for `egui`

**Comment by Jerrody** [comment]
> I agree with @RegenJacob because `egui_dock` is nothing more than just an extension for `egui`

Alright, anyway, a `quick start` guide (shot, but informative) is necessary.

**Comment by Adanos020** [comment]
@Jerrody Yup, just let's keep it to absolute minimum. A link to `egui` setup and a point about adding the `egui_dock` dependency should be enough.

**Comment by Jerrody** [comment]
> @Jerrody Yup, just let's keep it to absolute minimum. A link to `egui` setup and a point about adding the `egui_dock` dependency should be enough.

Maybe else explanation how to make the tabs layout? Well, at this week I will try to do something in this way.

**Comment by Adanos020** [comment]
@Jerrody But that's already in the documentation, right? I'd just link to that instead.

**Comment by Jerrody** [comment]
> @Jerrody But that's already in the documentation, right? I'd just link to that instead.

I would write it `README.md` reasons:
1) It's for the people to look into the `README.md` in `crates.io` or `GitHub` than look into the Rust docs
2) We could inline `README.md` into the code: `#![doc(include = "../README.md")]`

**Comment by Adanos020** [comment]
> I would write it in `README.md` reasons:
> 
> 1. It's for the people to look into the `README.md` in `crates.io` or `GitHub` than look into the Rust docs
> 2. We could inline `README.md` into the code: `#[doc = include_str!("../../README.md")]`

Okay, as long as this doesn't cause any issues (e.g. with the demo gif) then we can do that

**Comment by Jerrody** [comment]
> > I would write it in `README.md` reasons:
> > 
> > 1. It's for the people to look into the `README.md` in `crates.io` or `GitHub` than look into the Rust docs
> > 2. We could inline `README.md` into the code: `#[doc = include_str!("../../README.md")]`
> 
> Okay, as long as this doesn't cause any issues (e.g. with the demo gif) then we can do that

Very nice :D
