### ISSUE TITLE
Add community showcases of `egui_dock`

### ISSUE THREAD

**Issue by Jerrody** [Adanos020/egui_dock#75]
It's pretty hard for people to understand what exactly they can make with `egui_dock`. Maybe uncustomizable toy library or a very flexible builder for any kind of application like engine editors or desktop applications?

Showcase in `Markdown` (for example, `SHOWCASE.md`) or like in `imgui` with every release add showcases. Anyway, I think that we should make it, it inspires and people immidietly understand what they can make, and, of course, for the other people, it's possible to show their work.

**Comment by Adanos020** [comment]
I think this is more appropriate to be maintained by `egui`.
