### ISSUE TITLE
Prepare to the `0.3`

### ISSUE THREAD

**Issue by Jerrody** [Adanos020/egui_dock#76]
There're enough changes for the release, but before we do it.

TODO before release:
- [x] Merge https://github.com/Adanos020/egui_dock/pull/70
- [x] Update `README.md` and add `Quickstart` in `README.md

**Comment by RegenJacob** [comment]
I think it would be great to have #42 fixed as well before releasing major version

**Comment by 6361697897** [comment]
Sir help me sir

**Comment by Adanos020** [comment]
@Jerrody Looks like a spam account, I'll report it

**Comment by Jerrody** [comment]
> @Jerrody Looks like a spam account, I'll report it

Spam account on GitHub. It's something new =)
