### ISSUE TITLE
Proposal of contribution rules.

### ISSUE THREAD

**Issue by Jerrody** [Adanos020/egui_dock#8]
I think need to make a `CONTRIBUTING.md` guide that includes:
- Squashing commits. It's pretty hard to track commits if was made a PR that contains 2413241343242 commits and we merge it.
- Some code-style rules.

I can write this `CONTRIBUTING.md`.

**Comment by Adanos020** [comment]
Agree, let's do this

**Comment by Adanos020** [comment]
I'd also add some CI to check if the code is formatted with rustfmt, using our config which I can bring over from my other project.

**Comment by Jerrody** [comment]
> I'd also add some CI to check if the code is formatted with rustfmt, using our config which I can bring over from my other project.

I have already a made CI.
