### ISSUE TITLE
Splitter has wrong behavior when dragging

### ISSUE THREAD

**Issue by liquidhelium** [Adanos020/egui_dock#91]
**Describe the bug**
When the splitter is dragged out of the clamp range and back, it's in the wrong position.

**To Reproduce**
Just run the demo and drag the splitter.

**Expected behavior**
The splitter should always follow the pointer.

**Screenshots**
Here's a video showing different behaviors between `egui::DragValue` and splitters:

https://user-images.githubusercontent.com/59129152/213701383-c4a595e8-d4de-45ad-b683-b7c5338ea50e.mp4

**Additional context**
__Possible solution__: use another value to store the "last dragged value" (the same as DragValues do)  and clamp this value, not the splitters' position.
current code (hsplit): https://github.com/Adanos020/egui_dock/blob/bc489166c962562315ce1f8733de7f3acb95275c/src/style.rs#L178
We'll need to store `fraction` when dragging starts and use this value for clamping:
```rust
*fraction = (drag_start + delta / range).clamp(min, max); 
```

**Comment by liquidhelium** [comment]
Now I'm unsure about where to store this value, and is it enough to have one value for all `DockArea`s.

**Comment by liquidhelium** [comment]
Now I'm unsure about where to store this value and is it enough to have one value for all `DockArea`s.

**Comment by Adanos020** [comment]
Good find! We can try the approach you suggested, though it may also be possible to use pixel-perfect positions of the splitter and mouse cursor. That way we could avoid storing extra data for each split.

**Comment by liquidhelium** [comment]
I think all the splitters can use a same value, since only one splitter can be dragged at a time. Drag value used this solution.

**Comment by Adanos020** [comment]
Got it, thanks. Worth giving it a try.

**Comment by Adanos020** [comment]
Closed by #103
