### ISSUE TITLE
`.tabs_are_draggable(false)` makes tabs not clickable

### ISSUE THREAD

**Issue by grilme99** [Adanos020/egui_dock#92]
**Describe the bug**

Calling `StyleBuilder.tabs_are_draggable(false)` makes tabs not selectable, essentially breaking `egui_dock` because tabs can't be clicked between. 

**To Reproduce**

1. Create a new DockArea and set its style
2. Call `StyleBuilder.tabs_are_draggable(false)`
3. Run the app and try to switch between tabs

Example:

```rust
egui_dock::DockArea::new(&mut self.tree)
    .style(
        StyleBuilder::from_egui(ctx.style().as_ref())
            .tabs_are_draggable(false)
            .build(),
    )
    .show(ctx, &mut TopbarTabViewer);
```

**Expected behavior**

I expect tabs not to be draggable (as explained in the function description), but I still want to be able to switch between the tabs by clicking on them.

**Additional context**

I am on version `0.3.1` of `egui_dock`, `0.20.1` of `egui`, and `0.9.1` of `bevy`.

**Comment by Adanos020** [comment]
Thanks for reporting this, seems like a critical bug. I'll put fixing it on my priority list.
